### ISSUE TITLE
Fix random encoder jumps.

### ISSUE THREAD

**Issue by rezetta15** [FRC3636/frc-2024#75]

**Comment by doinkythederp** [comment]
We found part of the issue: WPILib's built-in DutyCycleEncoder class has support for wrapping, and whenever the encoder momentarily loses connection, the class thinks it has wrapped around and gone close to a full rotation. By using the `absolutePosition` value instead of the "wrappable" jumping version, we can remove this processing. This gets rid of random encoder jumps! Because our system is not continuous, we were then able to use modulo (not Euclidean remainder) to fix the remaining wrapping that came directly from the hardware.
